# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tempinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u6a21\u677f\u540d\u79f0')),
                ('font', models.CharField(max_length=5, verbose_name='\u5b57\u4f53\u4ee3\u7801')),
                ('fontsize', models.IntegerField(verbose_name='\u5b57\u4f53\u5927\u5c0f')),
                ('img', models.ImageField(upload_to='pyq_tool', verbose_name='\u6a21\u677f\u56fe\u7247')),
                ('imgsize', models.CharField(max_length=10, verbose_name='\u56fe\u7247\u5927\u5c0f')),
                ('icon', models.ImageField(upload_to='pyq_tool', verbose_name='\u56fe\u6807')),
                ('hint', models.CharField(max_length=10, verbose_name='\u8f93\u5165\u63d0\u793a')),
                ('textcolor', models.CharField(max_length=15, verbose_name='\u6587\u672c\u989c\u8272')),
                ('textplace', models.CharField(max_length=10, verbose_name='\u6587\u672c\u4f4d\u7f6e')),
                ('text2', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u65e5\u671f\u6587\u672c')),
                ('text2hint', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6587\u672c2\u63d0\u793a')),
                ('text2place', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u65e5\u671f\u4f4d\u7f6e')),
            ],
            options={
                'verbose_name': '\u7968\u5708\u795e\u5668',
                'verbose_name_plural': '\u7968\u5708\u795e\u5668',
            },
        ),
    ]
